# Generated by Django 3.2.3 on 2021-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='متن خبر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('source_link', models.URLField(verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['title'],
            },
        ),
    ]
