# Generated by Django 3.2.3 on 2021-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_link',
            field=models.URLField(blank=True, null=True, verbose_name='منبع'),
        ),
    ]
