# Generated by Django 3.2.3 on 2021-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_news_source_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس الکترونیکی')),
                ('phone_number', models.IntegerField(max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'پیام های تماس با ما',
                'ordering': ['-created'],
            },
        ),
    ]
