# Generated by Django 3.2.3 on 2021-05-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='author',
        ),
    ]
