# Generated by Django 3.2.3 on 2021-05-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210518_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0.0, verbose_name='قیمت'),
        ),
    ]
