# Generated by Django 3.2.3 on 2021-05-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'گالری تصاویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
    ]
